name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      # Needed for actions/checkout
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Show Rust toolchain (should be using rust-toolchain.toml)
        run: rustup show

      - name: Run tests
        run: cargo test --all

  build:
    name: "Build Image"
    runs-on: ubuntu-latest
    permissions:
      # Needed for actions/checkout
      contents: read
    steps:
      - name: checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Build Image
        run: podman build -t example-rust-http-service:${GITHUB_SHA} .

      - name: Sanity Check Image (Run container in background)
        run: podman run --rm -p 8080:8080 --name test_container -d example-rust-http-service:${GITHUB_SHA}

      - name: Sanity Check Image (Ensure GET /ping responds with HTTP 200)
        run: wget --retry-connrefused --waitretry=1 --timeout=5 --tries 20 --quiet --output-document=- localhost:8080/ping

      - name: Sanity Check Image (Clean up)
        if: always()
        run: podman container stop test_container
